sudo: required
services:
  - docker

before_install:
  - docker build -t emrossi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emrossi/react-test npm run test

after_success:
  - docker build -t emrossi/multi-client ./client
  - docker build -t emrossi/multi-nginx ./nginx
  - docker build -t emrossi/multi-server ./server
  - docker build -t emrossi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push emrossi/multi-client
  - docker push emrossi/multi-nginx
  - docker push emrossi/multi-server
  - docker push emrossi/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-256569700392'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY